### ISSUE TITLE
jobsCleanup issue

### ISSUE THREAD

**Issue by lrochette** [electric-cloud/EC-Admin#114]
Worked with Support to get an issue resolved where my jobsCleanup was dying quickly with a Null Pointer Exception.  We’ve gotten that addressed.  

But my recent jobs have been hanging and running but not completing.  I see that the script has a timeout of 600, any idea why my script isn’t timing out the steps running perpetually?  I put some logs in sharefile in our uploads/ directory and created a Laurent.Rochette directory.  Can you help me understand how to get my jobsCleanup to timeout these jobs that refuse to finish in reasonable time?

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-Admin#4
