### ISSUE TITLE
Add phased approach option to jobsCleanup

### ISSUE THREAD

**Issue by kmcknight** [electric-cloud/EC-Admin#120]
For very large jobs cleanup (e.g. 23k jobs), the background deleter can get overwhelmed and the EF server can wind up with stuck jobs that can't be aborted (other than by using KB article DB script). Splitting up the cleanup into smaller batches (e.g. one month's worth at a time)  can mitigate this problem (that was my manual solution - start by deleting jobs older than 9 months, then 8 months, on down to my required 3 month goal). Or possibly use a max count for 'createJobStep' call to ensure system is not overloaded.

**Comment by lrochette** [comment]
For a log of jobs to clean, there is another procedure called deleteObjects that is designed for such use cases.
However it does not delete the workspace directory
Give it a try and let me know

**Comment by kmcknight** [comment]
Oh! That's cool. That could work nicely, as it can be combined with a manually run 'find' command on the workspace (leveraging -mtime and -type) to remove actual workspace content once the jobs are gone.

**Comment by lrochette** [comment]
Tanay wrote that procedure for a customer with a lot to delete.
Honestly, @aahire should put that in the product. I've heard rumors about it but it's past due I think

**Comment by lrochette** [comment]
This has been implemented
