### ISSUE TITLE
Cannot promote EC-Admin

### ISSUE THREAD

**Issue by lrochette** [electric-cloud/EC-Admin#146]

**Comment by lrochette** [comment]
Marc reported the following error:

ectool --timeout 600 promotePlugin EC-Admin-3.1.8.715
ectool Errors detected during execution of plugin's ec_setup script: Exit code 1: ERROR: Publish failure: Unexpected retrieval exception for repository '': 'https://eflow.Corp.net:8200/artifacts/com.electriccloud/EC-Admin-Grapes/1.0.0': InternalError: Unexpected response code: [405]:

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-Admin#11
