### ISSUE TITLE
3.1.0 jar does not contain procedures

### ISSUE THREAD

**Issue by dhubbell** [electric-cloud/EC-Admin#148]
I downloaded the jar from the releases page as well as directly from the repo source and after importing, the plugin project shows no procedures and only a single ec_setup property in the project.  Clicking "promote" does not seem to do anything.

**Comment by dhubbell** [comment]
I take it back!  After the plugin promoted the procedures are present - it just took a lot longer than expected to promote

**Comment by lrochette** [comment]
Yes there is a performance issue with DSL. It makes for a great framework to create plugin but the promotion step is a lot longer (around 5 min)
