### ISSUE TITLE
jobsCleanup procedure will hang indefinitely if stuck waiting for a down resource

### ISSUE THREAD

**Issue by dhubbell** [electric-cloud/EC-Admin#149]
I had a resource that was down and the cleanup job ended up running for 9 days because it was waiting for the resource.  I'm editing the procedure to include a step timeout, but it would be good to include that in future versions as well.

**Comment by lrochette** [comment]
Please do a pull request if possible.

**Comment by lrochette** [comment]
@dhubbell can you confirm this one was fixed and I can close it please

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-Admin#10
