### ISSUE TITLE
Enhance jobsCleanup procedure to enable deletion of a smaller batch of jobs in a loop ( this number should be parameterized) , when trying to cleanup 1000s of jobs older than a certain number of days.

### ISSUE THREAD

**Issue by sureshvenkatesan** [electric-cloud/EC-Admin#158]
Improvement: Enhance   jobsCleanup procedure to enable deletion of a smaller batch of jobs in a loop ( this number should be parameterized)  , when trying to cleanup 1000s of jobs older than a certain number of days. Another option could be to limit the "Maximum number of jobs to delete"  in one run of jobsCleanup procedure.

Use-case:
When  EC-Admin jobsCleanup procedure is used to cleanup all  jobs  older than say 3 months ( and if there ares 1000s of jobs)  EC-Admin with then create  a large job with 1000s of dynamic steps . These dynamic steps are created to delete the workspace folder for each job step that ran on  remote agent with non-local workspace ( for the jobs to be cleaned/deleted by the EC-Admin jobsCleanup procedure) .  This can make EF server unusable  (due to NMB-24602  i.e no new jobs can run) until the clean job is completed.   If you try to abort  such a large  cleanup job  ,  that abort will also take several hours to  abort  all the dynamic steps  ( in  serial order) as seen in NMB-25946.  Then until the clean up  job is aborted no new jobs can run in EF. Hence we need the above mentioned improvement.

**Comment by sureshvenkatesan** [comment]
If you are doing findObjects  in a loop to determine the next set of job objects to mark for deletion ( using deleteObjects) , then as per NMB-17743 in the findObjects   use a filter like:
$ec->findObjects({objectType => 'job', filter => {operator => 'isNull', propertyName => 'deleted'}});

That will fetch only the objects that are not already marked for deletion. That way you can avoid trying to delete jobs that you already marked for deletion in previous loop ( and that will also avoid the NoSuchJob errors becuase by the time you try to remark for deletion the job was already deleted).

**Comment by lrochette** [comment]
@sureshvenkatesan can you have a look at https://github.com/electric-cloud/EC-Admin/pull/159 and flag any major issue please
