### ISSUE TITLE
changeBannerColor does not work properly on Windows Web server

### ISSUE THREAD

**Issue by lrochette** [electric-cloud/EC-Admin#169]
As reported in ZD #121981, when running on a windows web server, changeBannerColor returns

Copy failed: No such file or directory at C:\Users\ccbuild\AppData\Local\Temp\ecmdrAgent/agent.DQOLAFUD4L4IZUOT.run-3d1204a7-3544-11e9-b421-0050568a1d39-3d205d0d-3544-11e9-ac68-0050568a1d39.cmd line 38 

The error seem due to:

> BTW, when I define the universal plugins directory, I used backslashes (i.e. \\megatron\ecloud\ec_plugins), as I look at the EC-Admin MoveCopyLocal procedure of MoveOrCopy step script, it treaded the backslash as escape character, thus the srcFile path been set to path as '\megatronecloudec_plugins/EC-Admin-3.2.5.763/htdocs/logo-test-black.gif'! 
> 
> Also, according to the error, it failed in line 38 of updateCSSplatform step of file not found, but I do see css file exists in EC Web server path, not sure why the error showing "cmd" file not found.
>

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-Admin#8
