### ISSUE TITLE
Add a procedure  to check plugins

### ISSUE THREAD

**Issue by lrochette** [electric-cloud/EC-Admin#26]
ZD #133303

How do I get commander to check and upgrade my plugins? 

I have a set of plugins from Oct but they are out of date and 
at least one (EC-Homepage) is missing; as there is an error in GUI. 
How to I get commander to tell me what I need?

**Comment by lrochette** [comment]
@nikhilv can you shed some information on how to test version of plugin in the catalog?

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-Admin#12
