### ISSUE TITLE
Return size 0 if stat returns null

### ISSUE THREAD

**Issue by vijaybandari** [electric-cloud/EC-Admin#45]
stat returns null on symlink if its invalid (valid on actual resource where the job ran, but not on the resource where this cleanup job is running)
```perl
return $size if (! $st);
```
Adding above line at here will skip the invalid symlink in calculating size.
https://github.com/electric-cloud/EC-Admin/blob/master/src/project/procedures/deleteWorkspaceOrphans/steps/crawlWorkspace.pl#L114

**Comment by lrochette** [comment]
Thank you @vijaybandari for reporting this issue.
It has been fixed
