### ISSUE TITLE
ChangeTracking when plugin is created

### ISSUE THREAD

**Issue by lrochette** [electric-cloud/EC-Admin#48]
What happens when a plugin is created on a project where the project as the Change tracking enabled
Maybe I need to add a checkbox to deal with this

**Comment by lrochette** [comment]
it seems a few customers have run into issues where a plugin was modified by somebody and it broke stuff so having the option to enable Change tracking on the plugin is important

The question seems more around: do we need to bring the "source project" history along when the plugin is created.

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-Admin#15
