### ISSUE TITLE
Add procedure to modify memory setting on agent

### ISSUE THREAD

**Issue by lrochette** [electric-cloud/EC-Admin#62]
It's recommended by support to modify the Java memory settings for "special agents" like gateways, repo, web, ....
So create a procedure that would query the user for some value and replace them in the wrapper.conf

**Comment by lrochette** [comment]
First draft done but cannot restart the agent from a step
The agent stops but does not restart

**Comment by lrochette** [comment]
ON linux: by using the "at" command, I can create a restart of the server after it has stopped and I have lost control of my step

On Windows: so far I can only reboot the machine as scheduling a task requires a password.

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-Admin#17
