### ISSUE TITLE
Add pattern for SaveAllObjects

### ISSUE THREAD

**Issue by lrochette** [electric-cloud/EC-Admin#63]
Allow for pattern matching so that only objects that match the pattern are saved. This is particularly relevant when they want to export a single project and all related resources for that project.

**Comment by lrochette** [comment]
saveAllObjects is not intended to export individual objects but more as a global backup system.
Therefore I'm not leaning toward modifying it to accommodate this request.

Please let me know what I missed

**Comment by adeelmalik78** [comment]
We either enhance SaveAllObjects or create another procedure which allows users to export specific objects based on a pattern. For example, export only those objects that contain "_ABC_". This should capture projects, resources and whatever else matches this pattern.

**Comment by adeelmalik78** [comment]
Added these lines for each object that gets exported: 

`
  # if pattern is specified ...
  next if (index($pName, "$[pattern]") == -1);
`

**Comment by lrochette** [comment]
Thanks @adeelmalik78, I've modifed the code to allow for regular expression:

  # skip project that don't fit the pattern
  next if ($pName !~ /$pattern/ );
