### ISSUE TITLE
Add artifact export to saveAllObjects

### ISSUE THREAD

**Issue by lrochette** [electric-cloud/EC-Admin#72]
Would it be worth it to export artifact objects?
What about artifact version?

Is there enough information to justify the cost (time and space)?

**Comment by vidvijay** [comment]
Philips-Healthcare just asked for this.. they want to migrate their artifacts alone from one server environment to another.

**Comment by lrochette** [comment]
I can add Artifacts and AV easily.
For the artifact files themselves (in repository-date), there is a synchronization piece to copy those from an Artifact Repo server to another one. Would that be enough @vidvijay ?
If the meta data are copied, xcopy or rsync would be enough for the file part as well

**Comment by vidvijay** [comment]
Meta data copy is the most important part here for the customer. We are not syncing two repo servers defined on the same server though. These are completely different server installations with two different repo servers. So, an "export" of the meta data that can be "imported" into a different server is what they were looking for
