### ISSUE TITLE
Create a procedure to create a procedure using the new gradle process

### ISSUE THREAD

**Issue by lrochette** [electric-cloud/EC-Admin#85]
These are the changes @urvashisingh made to allow the plugin to be built using
the flow-gradle plugin.
- build.gradle sets up the plugin build based on the flow-gradle plugin.
- lib folder added - primarily required for GWT
-  Moved following folders:
  - /src/pages -> pages/
  - /src/out/staging/META-INF -> /src/main/resources/META-INF
  - /src/project -> /src/main/resources/project
- Renamed src/project/project.xml.in -> /src/main/resources/project/project.xml
- Replaced manifest.pl with an XML version in /src/main/resources/project/manifest.xml
- Deleted the src/out folder to avoid confusion

Other misc. changes:
- Added a .gitignore file
- Added license files and updated license in file headers
  (Used command 'gradlew licenseFormatMain' to apply license header)

So create a duplicate of projectAsCode to allow a project to be transformed into a plugin using this new Gradle system which the new default to create plugin.

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-Admin#18
