### ISSUE TITLE
project starting with _ cannot be saved on Windows

### ISSUE THREAD

**Issue by lrochette** [electric-cloud/EC-Admin#90]
From Noel:

edge case, there was a project that started with an underscore, and the export would not work on a windows server, path issue

Saving Project: _DH_MyFirstProject
  Saving Procedure: Advanced Data Structures – Lab 1
agent.ZMKSMCTJYP2C1543.run-6ee3b1ea-1076-11e6-af0e-0050569c683e-6efd540a-1076-11e6-9d27-0050569c683e error [IOException]: Couldn't write export file d:\ProgramData\Backup/Projects/_DH_MyFirstProject/Procedures/Advanced Data Structures – Lab 1/Advanced Data Structures – Lab 1.xml
    Details:
    Couldn't write export file d:\ProgramData\Backup/Projects/_DH_MyFirstProject/Procedures/Advanced Data Structures – Lab 1/Advanced Data Structures – Lab 1.xml

**Comment by lrochette** [comment]
@NoelS000 I can not reproduce the problem
I was able to create projects with one or 2 underscores in the name and backed them up with saveAllObjects without problem

Do you remember on what OS you were? I tried on Windows 7.

**Comment by NoelS000** [comment]
Maybe it was the funky special character underscore from PowerPoint??  I
don't remember what version of Windows, sorry
