### ISSUE TITLE
Enable additional files to be included in the plugin

### ISSUE THREAD

**Issue by gmaxey** [electric-cloud/EC-Admin#91]
Enable a developer to include html docs in htdocs directory or add a new directory with any files, such as DSL.

**Comment by lrochette** [comment]
There is already a mechanism to add directories by using the filesToCopy property. Check the help page and let me know if it does not meet your need

**Comment by gmaxey** [comment]
User error: I used the obsolete createPluginFromProject when I should have used projectAsCode.
