### ISSUE TITLE
Add jobName search to Job Cleanup

### ISSUE THREAD

**Issue by noels00** [electric-cloud/EC-Admin#96]
I had this request at Scottrade, and now at Tibco as well

Users would like to be able to clean up specific jobs (i.e. by jobName).  For example, they may want to cleanup all jobs older than 6 months, but would like to additionally cleanup all jobs that begin with"XYZ" that are older than just 2 weeks.  So a specific user may run a job multiple times a day and may want to only save a small list (i.e. the last 2 weeks only), so he wants to cleanup only his specific jobs that are of the jobName format XYZ*

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/EC-Admin#20
